SUBREDDITS_LIST = [
    "askreddit",
    "askscience",
    "books",
    "business",
    "cars",
    "casualconversation",
    # "changemyview",
    # "explainlikeimfive",
    # "games",
    # "history",
    # "hockey",
    # "iama",
    # "movies",
    # "music",
    # "news",
    # "offmychest",
    # "philosophy",
    # "politics",
    # "showerthoughts",
    # "technology",
    # "teenagers",
    # "tipofmytongue",
    # "todayilearned",
    # "travel",
    # "unpopularopinion",
    # "worldnews",
    # "worldpolitics",
]
