SUBREDDITS_LIST = [
    "movies",
    # "music",
    # "todayilearned",
    # "askreddit",
    # "unpopularopinion",
    # "worldnews",
    # "news",
    # "politics",
    # "showerthoughts",
    # "teenagers",
    # "history",
    # "changemyview",
    # "explainlikeimfive",
    # "books",
    # "games",
    # "technology",
    # "travel",
    # "offmychest",
    # "cars",
    # "worldpolitics",
    # "askscience",
    # "casualconversation",
    # "tipofmytongue",
    # "iama",
    # "hockey",
    # "philosophy",
    # "business",
    # "nostupidquestions",
    # "outoftheloop",
    # "askhistorians",
    # "science",
    # "jokes",
    # "television",
    # "programming",
    # "boardgames",
    # "askmen",
    # "askwomen",
    # "crazyideas",
    # "hiphopheads",
    # "apple",
    # "tooafraidtoask",
    # "lifeprotips",
    # "nottheonion",
    # "space",
    # "gadgets",
    # "upliftingnews",
    # "tifu",
    # "futurology",
    # "writingprompts",
    # "nosleep",
    # "twoxchromosomes",
    # "personalfinance",
    # "dadjokes",
    # "iphone",
    # "android",
    # "buildapc",
    # "confession",
    # "fitness",
    # "leagueoflegends",
    # "relationships",
    # "atheism",
    # "relationship_advice",
    # "gameofthrones",
    # "youshouldknow",
    # "parenting"
]

COMMON_WORDS = [
    "the",
    "of",
    "and",
    "not",
    "or",
    "but",
    "to",
    "in",
    "on",
    "for",
    "is",
    "was",
    "are",
    "were",
    "i",
    "you",
    "we",
    "he",
    "she",
    "it",
    "be",
    "an",
    "can",
    "if",
    "a",
]
